Personal trainer register
TreinaDev/esperto-fit-clientes pull request #23
Opened 2020-10-01 20:47 UTC by Periiz

Estamos trabalhando no registro de Personal Trainer

Co-authored-by: Reinaldo Luiz <reinaldolluiz@gmail.com>

2020-10-05 20:55 UTC, akaninja requested changes
Parece ok! Talvez incluindo testes unitários já daria pra fechar.

2020-10-05 20:55 UTC, akaninja commented on spec/features/personal_trainer_register_spec.rb
> +    expect(page).to have_content('não pode ficar em branco', count: 5)
Que tal incluir cada uma das mensagens de validação dos atributos traduzidos?

2020-10-05 20:55 UTC, akaninja commented on spec/features/personal_trainer_register_spec.rb
> +    expect(page).to have_content('CREF inválido')
Que acham de fazer uns testes unitários dessas validações?

2020-10-05 20:55 UTC, akaninja commented on app/models/personal.rb
> +  validates :cref, format: { with: %r'\d{6}-[G|P]/\w{2}', message: 'CREF inválido' }
Talvez colocar no i18n essas mensagens de validação?

2020-10-05 22:31 UTC, HenriqueMorato reviewed
Acho que um comentário geral é que poderiam verificar o uso de i18n em alguns lugares.

2020-10-05 22:31 UTC, HenriqueMorato commented on app/models/personal.rb
> +  validates :cref, format: { with: %r'\d{6}-[G|P]/\w{2}', message: 'CREF inválido' }
```suggestion
  validates :cref, format: { with: %r { \d{6}-[G|P]/\w{2} }, message: 'CREF inválido' }
```

2020-10-05 22:31 UTC, HenriqueMorato commented on config/locales/pt-BR.yml
> +      create: Enviar
Acho que essa customização é melhor fazer só na view de vocês o que acham?

2020-10-06 14:41 UTC, Periiz commented on spec/features/personal_trainer_register_spec.rb
> +    expect(page).to have_content('não pode ficar em branco', count: 5)
Acho que fica melhor pra saber o que que o teste deveria procurar, mesmo.

2020-10-06 15:08 UTC, Periiz commented on config/locales/pt-BR.yml
> +      create: Enviar
A gente queria evitar ficar colocando tradução nas views, e como a gente imaginou que em nenhum lugar do sistema um usuário "criaria" algo, seria ok mudar na tradução, mesmo. Mas talvez não seja. Vou colocar na view mesmo, então (:

2020-10-06 15:11 UTC, Periiz commented on app/models/personal.rb
> +  validates :cref, format: { with: %r'\d{6}-[G|P]/\w{2}', message: 'CREF inválido' }
No I18n já tem uma mensagem de inválido, na verdade.
Se apagar esse trecho com a mensagem, vai aparecer "não é válido" ao invés de "inválido". Talvez seja melhor simplesmente não colocar mensagem customizada e deixar o que já tinha no I18n?

2020-10-06 15:20 UTC, Periiz commented on app/models/personal.rb
> +  validates :cref, format: { with: %r'\d{6}-[G|P]/\w{2}', message: 'CREF inválido' }
Na verdade acho que isso também vale pro CPF, já que tem uma mensagem customizada na validação dele que podia simplesmente ser o que já tinha no I18n. :0

2020-10-06 15:46 UTC, Periiz commented on spec/features/personal_trainer_register_spec.rb
> +    expect(page).to have_content('CREF inválido')
Acho uma muito boa ideia! Fomos deixar pra depois e acabamos esquecendo, parece :(

2020-10-06 20:00 UTC, HenriqueMorato approved these changes

2020-10-07 15:27 UTC, merged