Personal cancel ordered appointment
TreinaDev/esperto-fit-clientes pull request #41
Opened 2020-10-13 12:24 UTC by Paulo-Rodrigues

Este pull request implementa a função de um personal devidamente logado cancelar o agendamento de um treino/aula.

2020-10-13 13:57 UTC, joaorsalmeida commented on app/controllers/appointments_controller.rb
> +  def cancel
Seria importante garantir que o personal que está cancelando é o personal desse agendamento, não acha?

2020-10-13 13:59 UTC, joaorsalmeida requested changes
Paulo, o código está certinho mas encontrei dois pontos de autenticação/autorização que me chamaram atenção. Você pode verificar?

2020-10-13 17:22 UTC, Paulo-Rodrigues commented on app/controllers/appointments_controller.rb
> +  def cancel
Sim, tem razão. Desatenção de minha parte

2020-10-13 17:26 UTC, Paulo-Rodrigues commented on spec/features/order_appointments/personal_cancel_order_appointment_spec.rb
> +    visit appointment_path(appointment)
Bom ponto, outra desatenção de minha parte. Mas uma dúvida, nesse caso específico precisamos que dois objetos (client e personal) tenham acesso ao mesmo recurso/action (show action de appointment no caso). Usar before_action :authenticate_(client/personal) acho que um sobrescreve o outro, não ? Como seria uma possível solução nesse caso ?

2020-10-13 19:30 UTC, HenriqueMorato commented on config/routes.rb
> +      put 'appointments/:id', to: 'appointments#cancel', as: :cancel
Aqui não poderia ter uma rota de cancelar mesmo? Só pra manter porque no futuro vocês podem querer editar o appointment por algum motivo e ficou uma rota travada.

2020-10-19 23:04 UTC, Paulo-Rodrigues commented on config/routes.rb
> +      put 'appointments/:id', to: 'appointments#cancel', as: :cancel
Não sei se entendi direito, mas acredito que por enquanto da pra seguir assim.

2020-10-21 21:43 UTC, merged