Consumir api de CPF de empresa parceira
TreinaDev/esperto-fit-clientes pull request #48
Opened 2020-10-14 14:19 UTC by Paulo-Rodrigues

Este PR implementa a forma de consumo/acesso ao sistema de promoções para verificação de cpf de um cliente que possua parceria com a esperto-fit

2020-10-14 16:19 UTC, HenriqueMorato commented on app/models/client.rb
> +  # end
Achei extrair essa regra pra um use case legal mas como não existe outros ainda gera uma complexidade desnecessária. O que você acha sobre isso? Novas regras como essa vão surgir?

2020-10-14 16:56 UTC, Paulo-Rodrigues commented on app/models/client.rb
> +  # end
Era pra ter apagado isso, pertencia a uma implementação anterior. Vamos corrigir.

2020-10-14 16:56 UTC, Paulo-Rodrigues commented on app/models/client/partner_client.rb
> +    VerifyPartnershipService.new(self).call
Boa, bem legal mesmo, vamos modificar.

2020-10-15 19:38 UTC, joaorsalmeida requested changes
Pessoal, aqui pra mim o mock passou um pouco a linha. Está tudo 100% mockado mas em nenhum momento vocês realmente consomem um JSON e garantem que os métodos extraem corretamente os dados deste JSON, me entendem? 

E como já falamos por audio, acredito que módulo não é a estrutura adequada. Client ou PartnerClient deveria ser um PORO e vocês poderiam manipular objetos inteiros criados a partir do resultado de uma chamada à API.

2020-10-19 18:29 UTC, HenriqueMorato approved these changes

2020-10-21 22:01 UTC, merged